In [3]:
df = pd.read_csv('All_routes_links.csv')
df

,route_name,route_link
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa
1,Bangalore to Goa,https://www.redbus.in/bus-tickets/bangalore-to...
2,Mumbai to Goa,https://www.redbus.in/bus-tickets/mumbai-to-goa
3,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune
4,Belagavi to Goa,https://www.redbus.in/bus-tickets/belagavi-to-goa
...,...,...
165,Marcel to Belagavi,https://www.redbus.in/bus-tickets/marcel-to-be...
166,Belagavi to Marcel,https://www.redbus.in/bus-tickets/belagavi-to-...
167,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa
168,Goa to Sangola (Solapur),https://www.redbus.in/bus-tickets/goa-to-sangola
169,Calangute (goa) to Goa Airport,https://www.redbus.in/bus-tickets/calangute-go...

In [ ]:

from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

driver = webdriver.Chrome()
driver.maximize_window()

all_buses_data = []

for i,r in df.iterrows():
    link=r["route_link"]
    route=r["route_name"]

    # Loop through each link
    driver.get(link)
    time.sleep(3)
    
    
    try:
        button = driver.find_elements(By.XPATH, "//div[@class='button']")
        button[0].click()
        time.sleep(3)
    except Exception as e:
        print("No button found or unable to click:", e)
        

    bus_names = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_types = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    departing_times = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
    duration_times = driver.find_elements(By.XPATH, "//div[@class='dur l-color lh-24']")
    reaching_times = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
    star_ratings = driver.find_elements(By.XPATH, "//div[@class='lh-18 rating rat-green ']")
    prices = driver.find_elements(By.XPATH, "//div[@class='fare d-block']")
    seats_availabilities = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-16']")
    #print(bus_name,bus_type,departing_time,duration_time,reaching_time,star_rating,price,seats_availability)


    for idx in range(len(bus_names)):
        bus_data = {
            "route": route,
            "link": link,
            "Bus Name": bus_names[idx].text,
            "Bus Type": bus_types[idx].text if idx < len(bus_types) else "N/A",
            "Departing Time": departing_times[idx].text if idx < len(departing_times) else "N/A",
            "Duration Time": duration_times[idx].text if idx < len(duration_times) else "N/A",
            "Reaching Time": reaching_times[idx].text if idx < len(reaching_times) else "N/A",
            "Star Rating": star_ratings[idx].text if idx < len(star_ratings) else "N/A",
            "Price": prices[idx].text if idx < len(prices) else "N/A",
            "Seats Availability": seats_availabilities[idx].text if idx < len(seats_availabilities) else "N/A",
        }
        all_buses_data.append(bus_data)
        print(bus_data)

No button found or unable to click: list index out of range
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '22:30', 'Duration Time': '11h 10m', 'Reaching Time': '09:40', 'Star Rating': '4.5', 'Price': '3077', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '21:45', 'Duration Time': '11h 10m', 'Reaching Time': '08:55', 'Star Rating': '4.3', 'Price': '2954', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Ashray Grand', 'Bus Type': 'Volvo Multi-Axle A/C Sleeper (2+1)', 'Departing Time': '21:30', 'Duration Time': '12h 30m', 'Reaching Time': '10:00', 'Star Rating': '4.1', 'Price': 'INR 3400', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'AdAnand Tours And Travels', 'Bus Type': 'Volvo Multi-Axle I-Shift A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '12h 45m', 'Reaching Time': '08:45', 'Star Rating': '4.3', 'Price': 'INR 3200', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Intercity travels', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '14h 00m', 'Reaching Time': '10:00', 'Star Rating': '4.6', 'Price': 'INR 3999', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '14h 25m', 'Reaching Time': '10:15', 'Star Rating': '4.5', 'Price': 'INR 2234', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Streamline tours and travels', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '14h 20m', 'Reaching Time': '10:10', 'Star Rating': '4.1', 'Price': 'INR 3749', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Suprith Holidays', 'Bus Type': '', 'Departing Time': '19:55', 'Duration Time': '13h 35m', 'Reaching Time': '09:30', 'Star Rating': 'N/A', 'Price': '', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': 'N/A', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '13h 35m', 'Reaching Time': '09:40', 'Star Rating': '4.5', 'Price': '3071', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '15h 55m', 'Reaching Time': '11:55', 'Star Rating': '4.5', 'Price': '4786', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '13h 05m', 'Reaching Time': '08:55', 'Star Rating': '4.4', 'Price': '2891', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '12h 45m', 'Reaching Time': '08:35', 'Star Rating': '4.3', 'Price': 'INR 3309', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'Laxmi holidays', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '10h 55m', 'Reaching Time': '07:00', 'Star Rating': '4.6', 'Price': 'INR 750', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '09h 35m', 'Reaching Time': '05:40', 'Star Rating': '4.4', 'Price': 'INR 600', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '11h 00m', 'Reaching Time': '07:00', 'Star Rating': '4.2', 'Price': '900', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'AdAnand Ashray Travels', 'Bus Type': 'Volvo Multi-Axle I-Shift A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '10h 10m', 'Reaching Time': '06:00', 'Star Rating': '', 'Price': 'INR 999', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': 'N/A', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
{'route': 'Goa to Mumbai', 'link': 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Bus Name': 'Laxmi holidays', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '14h 15m', 'Reaching Time': '10:15', 'Star Rating': '4.5', 'Price': 'INR 800', 'Seats Availability': 'N/A'}
{'route': 'Goa to Mumbai', 'link': 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '15h 55m', 'Reaching Time': '11:55', 'Star Rating': '4.3', 'Price': '1000', 'Seats Availability': 'N/A'}
{'route': 'Goa to Mumbai', 'link': 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Bus Name': 'Rajdhani Travels Corporation', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '12h 10m', 'Reaching Time': '08:10', 'Star Rating': '4.3', 'Price': 'INR 1000', 'Seats Availability': 'N/A'}
{'route': 'Goa to Mumbai', 'link': 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Bus Name': 'AdIntrCity SmartBus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '15h 45m', 'Reaching Time': '11:45', 'Star Rating': '4.5', 'Price': 'INR 1000', 'Seats Availability': 'N/A'}
{'route': 'Goa to Mumbai', 'link': 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Bus Name': 'Rajdhani Travels Corporation', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '20:30', 'Duration Time': '10h 15m', 'Reaching Time': '06:45', 'Star Rating': 'N/A', 'Price': 'INR 1000', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Goa to Belagavi', 'link': 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Bus Name': 'PVS Tours and Travels', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '02h 45m', 'Reaching Time': '22:45', 'Star Rating': '3.4', 'Price': 'INR 1099', 'Seats Availability': '9 Seats available'}
{'route': 'Goa to Belagavi', 'link': 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Bus Name': 'S R Travels', 'Bus Type': 'NON A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '03h 59m', 'Reaching Time': '23:59', 'Star Rating': 'N/A', 'Price': 'INR 800', 'Seats Availability': '1 Seat available'}
{'route': 'Goa to Belagavi', 'link': 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Bus Name': 'Taruni Trans & Logistics', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:45', 'Duration Time': '08h 00m', 'Reaching Time': '03:45', 'Star Rating': 'N/A', 'Price': '4500', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Goa to Bangalore', 'link': 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Bus Name': 'Intercity travels', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '19:57', 'Duration Time': '10h 33m', 'Reaching Time': '06:30', 'Star Rating': '4.4', 'Price': 'INR 999', 'Seats Availability': 'N/A'}
{'route': 'Goa to Bangalore', 'link': 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Bus Name': 'Streamline tours and travels', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '20:20', 'Duration Time': '11h 10m', 'Reaching Time': '07:30', 'Star Rating': '4.0', 'Price': 'INR 999', 'Seats Availability': 'N/A'}
{'route': 'Goa to Bangalore', 'link': 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'AC Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '11h 20m', 'Reaching Time': '07:20', 'Star Rating': '4.3', 'Price': 'INR 799', 'Seats Availability': 'N/A'}
{'route': 'Goa to Bangalore', 'link': 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
{'route': 'Goa to Bangalore', 'link': 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
{'route': 'Goa to Kolhapur(Maharashtra)', 'link': 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '05h 35m', 'Reaching Time': '01:25', 'Star Rating': '4.4', 'Price': '547', 'Seats Availability': 'N/A'}
{'route': 'Goa to Kolhapur(Maharashtra)', 'link': 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '05h 30m', 'Reaching Time': '01:35', 'Star Rating': '4.7', 'Price': 'INR 420', 'Seats Availability': 'N/A'}
{'route': 'Goa to Kolhapur(Maharashtra)', 'link': 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:50', 'Duration Time': '05h 35m', 'Reaching Time': '02:25', 'Star Rating': '4.4', 'Price': '449', 'Seats Availability': 'N/A'}
{'route': 'Goa to Kolhapur(Maharashtra)', 'link': 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Bus Name': 'Laxmi-Princess Nova', 'Bus Type': 'Non A/C Seater / Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '05h 40m', 'Reaching Time': '01:30', 'Star Rating': 'N/A', 'Price': 'INR 599', 'Seats Availability': 'N/A'}
{'route': 'Goa to Kolhapur(Maharashtra)', 'link': 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Bus Name': 'Atmaram Travels(GTA)', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:40', 'Duration Time': '06h 05m', 'Reaching Time': '01:45', 'Star Rating': 'N/A', 'Price': 'INR 1000', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
{'route': 'Solapur to Goa', 'link': 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Bus Name': 'Sharma Travels', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '23:00', 'Duration Time': '10h 00m', 'Reaching Time': '09:00', 'Star Rating': '4.6', 'Price': 'INR 1300', 'Seats Availability': 'N/A'}
{'route': 'Solapur to Goa', 'link': 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Bus Name': 'Sharma Travels', 'Bus Type': 'AC Sleeper (2+1)', 'Departing Time': '22:00', 'Duration Time': '10h 00m', 'Reaching Time': '08:00', 'Star Rating': '4.4', 'Price': 'INR 1200', 'Seats Availability': 'N/A'}
{'route': 'Solapur to Goa', 'link': 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Bus Name': 'Sharma Travels', 'Bus Type': 'AC Sleeper (2+1)', 'Departing Time': '22:30', 'Duration Time': '10h 00m', 'Reaching Time': '08:30', 'Star Rating': '4.0', 'Price': 'INR 1200', 'Seats Availability': 'N/A'}
{'route': 'Solapur to Goa', 'link': 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Bus Name': 'Khurana Travel Services', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '22:15', 'Duration Time': '09h 15m', 'Reaching Time': '07:30', 'Star Rating': 'N/A', 'Price': 'INR 1200', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
No button found or unable to click: list index out of range
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '22:30', 'Duration Time': '11h 10m', 'Reaching Time': '09:40', 'Star Rating': '4.5', 'Price': '3077', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '21:45', 'Duration Time': '11h 10m', 'Reaching Time': '08:55', 'Star Rating': '4.3', 'Price': '2954', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'Ashray Grand', 'Bus Type': 'Volvo Multi-Axle A/C Sleeper (2+1)', 'Departing Time': '21:30', 'Duration Time': '12h 30m', 'Reaching Time': '10:00', 'Star Rating': '4.1', 'Price': 'INR 3400', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': 'AdAnand Tours And Travels', 'Bus Type': 'Volvo Multi-Axle I-Shift A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '12h 45m', 'Reaching Time': '08:45', 'Star Rating': '4.3', 'Price': 'INR 3200', 'Seats Availability': 'N/A'}
{'route': 'Pune to Goa', 'link': 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Intercity travels', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '14h 00m', 'Reaching Time': '10:00', 'Star Rating': '4.6', 'Price': 'INR 3999', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '14h 25m', 'Reaching Time': '10:15', 'Star Rating': '4.5', 'Price': 'INR 2234', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Streamline tours and travels', 'Bus Type': 'A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '14h 20m', 'Reaching Time': '10:10', 'Star Rating': '4.1', 'Price': 'INR 3749', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': 'Suprith Holidays', 'Bus Type': '', 'Departing Time': '19:55', 'Duration Time': '13h 35m', 'Reaching Time': '09:30', 'Star Rating': 'N/A', 'Price': '', 'Seats Availability': 'N/A'}
{'route': 'Bangalore to Goa', 'link': 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': 'N/A', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '13h 35m', 'Reaching Time': '09:40', 'Star Rating': '4.5', 'Price': '3071', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '15h 55m', 'Reaching Time': '11:55', 'Star Rating': '4.5', 'Price': '4786', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'Bharat Benz A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '13h 05m', 'Reaching Time': '08:55', 'Star Rating': '4.4', 'Price': '2891', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '12h 45m', 'Reaching Time': '08:35', 'Star Rating': '4.3', 'Price': 'INR 3309', 'Seats Availability': 'N/A'}
{'route': 'Mumbai to Goa', 'link': 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Bus Name': '', 'Bus Type': '', 'Departing Time': '', 'Duration Time': '', 'Reaching Time': '', 'Star Rating': '', 'Price': '', 'Seats Availability': 'N/A'}
No button found or unable to click: list index out of range
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'Laxmi holidays', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '10h 55m', 'Reaching Time': '07:00', 'Star Rating': '4.6', 'Price': 'INR 750', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'IntrCity SmartBus', 'Bus Type': 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Departing Time': '20:05', 'Duration Time': '09h 35m', 'Reaching Time': '05:40', 'Star Rating': '4.4', 'Price': 'INR 600', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'Zingbus Plus', 'Bus Type': 'VE A/C Sleeper (2+1)', 'Departing Time': '20:00', 'Duration Time': '11h 00m', 'Reaching Time': '07:00', 'Star Rating': '4.2', 'Price': '900', 'Seats Availability': 'N/A'}
{'route': 'Goa to Pune', 'link': 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Bus Name': 'AdAnand Ashray Travels', 'Bus Type': 'Volvo Multi-Axle I-Shift A/C Sleeper (2+1)', 'Departing Time': '19:50', 'Duration Time': '10h 10m', 'Reaching Time': '06:00', 'Star Rating': '', 'Price': 'INR 999', 'Seats Availability': 'N/A'}

In [12]:
df1 = pd.DataFrame(all_buses_data)
df1

,route,link,Bus Name,Bus Type,Departing Time,Duration Time,Reaching Time,Star Rating,Price,Seats Availability
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Zingbus Plus,Bharat Benz A/C Sleeper (2+1),22:30,11h 10m,09:40,4.5,3077,N/A
1,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Zingbus Plus,Bharat Benz A/C Sleeper (2+1),21:45,11h 10m,08:55,4.3,2954,N/A
2,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Ashray Grand,Volvo Multi-Axle A/C Sleeper (2+1),21:30,12h 30m,10:00,4.1,INR 3400,N/A
3,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,AdAnand Tours And Travels,Volvo Multi-Axle I-Shift A/C Sleeper (2+1),20:00,12h 45m,08:45,4.3,INR 3200,N/A
4,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,,,,,,,,N/A
...,...,...,...,...,...,...,...,...,...,...
411,Goa to Kolhapur(Maharashtra),https://www.redbus.in/bus-tickets/goa-to-kolha...,Kelkar Travels Garuda,Non A/C Seater / Sleeper (2+1),19:50,06h 40m,02:30,N/A,INR 600,N/A
412,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,Bharat Benz A/C Sleeper (2+1),23:00,10h 00m,09:00,4.6,INR 1300,N/A
413,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,AC Sleeper (2+1),22:00,10h 00m,08:00,4.4,INR 1200,N/A
414,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,AC Sleeper (2+1),22:30,10h 00m,08:30,4.0,INR 1200,N/A
415,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Khurana Travel Services,A/C Sleeper (2+1),22:15,09h 15m,07:30,N/A,INR 1200,N/A

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   route               416 non-null    object
 1   link                416 non-null    object
 2   Bus Name            416 non-null    object
 3   Bus Type            416 non-null    object
 4   Departing Time      416 non-null    object
 5   Duration Time       416 non-null    object
 6   Reaching Time       416 non-null    object
 7   Star Rating         416 non-null    object
 8   Price               416 non-null    object
 9   Seats Availability  416 non-null    object
dtypes: object(10)
memory usage: 32.6+ KB

In [34]:
import mysql.connector

# Database configuration
conn = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'Dheeraj@123',
    database = 'vasan',
    port = 3306
    
)
# Connect to MySQL server (no DB yet)

cursor = conn.cursor()



# Create table
create_table_query = """
CREATE TABLE IF NOT EXISTS bus_routes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    route_name TEXT,
    route_link TEXT,
    busname TEXT,
    bustype TEXT,
    price DECIMAL(10,2),
    seats_available INT,
    departing_time TIME,
    duration TEXT,
    reaching_time TIME,
    star_rating FLOAT
);
"""
cursor.execute(create_table_query)
print("✅ Table 'bus_routes' created.")

insert_query = """
INSERT INTO bus_routes (
    route_name, route_link, busname, bustype, price, seats_available,
    departing_time, duration, reaching_time, star_rating
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# Insert data into the table
for bus in all_buses_data:
    # Convert price to a numeric value and handle missing or invalid data
    price = float(bus["Price"].replace("INR", "").strip()) if bus["Price"] and "INR" in bus["Price"] else None
    seats_available = int(bus["Seats Availability"].split()[0]) if bus["Seats Availability"] and "Seats" in bus["Seats Availability"] else None
    star_rating = float(bus["Star Rating"]) if bus["Star Rating"] and bus["Star Rating"] != "N/A" else None

    values = (
        bus["route"],
        bus["link"],
        bus["Bus Name"],
        bus["Bus Type"],
        price,
        seats_available,
        bus["Departing Time"] if bus["Departing Time"] else None,
        bus["Duration Time"] if bus["Duration Time"] else None,
        bus["Reaching Time"] if bus["Reaching Time"] else None,
        star_rating,
    )
    cursor.execute(insert_query, values)

conn.commit()
print("✅ Data inserted into 'bus_routes' table.")

✅ Table 'bus_routes' created.
✅ Data inserted into 'bus_routes' table.

In [35]:
df1.to_csv('All_routes_buses.csv', index=False)
df1

,route,link,Bus Name,Bus Type,Departing Time,Duration Time,Reaching Time,Star Rating,Price,Seats Availability
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Zingbus Plus,Bharat Benz A/C Sleeper (2+1),22:30,11h 10m,09:40,4.5,3077,N/A
1,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Zingbus Plus,Bharat Benz A/C Sleeper (2+1),21:45,11h 10m,08:55,4.3,2954,N/A
2,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Ashray Grand,Volvo Multi-Axle A/C Sleeper (2+1),21:30,12h 30m,10:00,4.1,INR 3400,N/A
3,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,AdAnand Tours And Travels,Volvo Multi-Axle I-Shift A/C Sleeper (2+1),20:00,12h 45m,08:45,4.3,INR 3200,N/A
4,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,,,,,,,,N/A
...,...,...,...,...,...,...,...,...,...,...
411,Goa to Kolhapur(Maharashtra),https://www.redbus.in/bus-tickets/goa-to-kolha...,Kelkar Travels Garuda,Non A/C Seater / Sleeper (2+1),19:50,06h 40m,02:30,N/A,INR 600,N/A
412,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,Bharat Benz A/C Sleeper (2+1),23:00,10h 00m,09:00,4.6,INR 1300,N/A
413,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,AC Sleeper (2+1),22:00,10h 00m,08:00,4.4,INR 1200,N/A
414,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Sharma Travels,AC Sleeper (2+1),22:30,10h 00m,08:30,4.0,INR 1200,N/A
415,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa,Khurana Travel Services,A/C Sleeper (2+1),22:15,09h 15m,07:30,N/A,INR 1200,N/A